### ISSUE TITLE
Move ComponentCacheActivity to Application

### ISSUE THREAD

**Issue by chijikpijik** [grandstaish/compartment#1]
Hi!
Why did you move ComponentCacheActivity's NonConfigurationInstance behaviour to an Application?
Is onRetainCustomNonConfigurationInstance method bad?
Thanks!

**Comment by grandstaish** [comment]
I don't think it's bad at all. I'd say the activity non-configuration approach is arguably better; that's how retained fragments work. I'm leaving it in the Application class for now because consumers might expect presenter instances to be retained when Activities get destroyed in the background (simulated using the developer option "Don't keep activities" and backgrounding the app then returning to the app afterwards).

**Comment by michal-luszczuk** [comment]
Hello,
First of all, I think that using setRetainInstance(true) on fragments to hold presenters inside of them is not a good idea because:
1. retained fragments could not be used properly with fragment back stack
2. retained fragments could not be nested (used in childFragmentManager)
That's why using onRetainCustomNonConfigurationInstance is way better, because we could still use fragment at any way we want, and handle config changes properly.

Secondly, storing Presenters in Application singleton is not good idea. 
Presenters are used in activities (or their subcomponents - Fragments) and this is their scope of life and responsibility. 
If presenter "A" is currently holding reference to some data model (memory consuming structure) or connection for example in activity "A" and we are going deep into our app opening other activities... if app needs memory (like you said - we could simulate it using "don't keep activities") activity A will be destroyed and I think our presenter should also, because what is the explanation for wasting memory?
Presenter should be destroyed like activity when app needs memory for some other currently used activities and storing all references in Application object is kind of unnecessary overhead.
And overtaking questions about long run tasks that should live longer than their activities where they are used - if they are long (and not strictly Activity related) they should be called from/in Service. If not long, from Presenter and live in memory only as long as Activity is.

Btw. great library :+1:

**Comment by grandstaish** [comment]
I think you're right. I'm open to a pull request, or otherwise i'll push an update in the future when I get a bit of time.

**Comment by grandstaish** [comment]
Fixed in 71dcc58
